addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.+")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.+")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.+")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.+")
addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "1.0.+")
addSbtPlugin("com.scalapenos" % "sbt-prompt" % "1.0.2")